/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        "secondary-fixed": "#e2e2e2",
        background: "#131313",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#454747",
        "secondary-fixed-dim": "#c6c6c7",
        "on-tertiary": "#313030",
        "surface-container-lowest": "#0e0e0e",
        "surface-variant": "#353534",
        "on-secondary-container": "#b4b5b5",
        "on-error": "#690005",
        "on-primary-fixed": "#001f24",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#00363d",
        "outline-variant": "#3b494c",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#bac9cc",
        "on-secondary-fixed-variant": "#454747",
        "surface-container": "#201f1f",
        "on-primary-container": "#00626e",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-bright": "#3a3939",
        secondary: "#c6c6c7",
        tertiary: "#efeceb",
        "primary-fixed-dim": "#00daf3",
        "on-tertiary-fixed-variant": "#474746",
        "on-error-container": "#ffdad6",
        "on-secondary": "#2f3131",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary-fixed-variant": "#004f58",
        "surface-tint": "#00daf3",
        "inverse-primary": "#006875",
        "tertiary-fixed": "#e5e2e1",
        "primary-container": "#00e5ff",
        "surface-container-low": "#1c1b1b",
        surface: "#131313",
        "error-container": "#93000a",
        outline: "#849396",
        "tertiary-container": "#d2d0cf",
        "on-tertiary-container": "#5a5959",
        "surface-container-highest": "#353534",
        error: "#ffb4ab",
        "primary-fixed": "#9cf0ff",
        primary: "#c3f5ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        "stack-sm": "16px",
        gutter: "24px",
        unit: "8px",
        "section-padding": "80px",
        "stack-md": "32px",
      },
      fontFamily: {
        "ui-button": ["Manrope"],
        "body-lg": ["Manrope"],
        "display-lg-mobile": ["Noto Serif"],
        "display-lg": ["Noto Serif"],
        "headline-md": ["Noto Serif"],
        "body-md": ["Manrope"],
        "label-caps": ["Space Grotesk"],
      },
      fontSize: {
        "ui-button": ["15px", { lineHeight: "1.0", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["14px", { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};
